In [1]:
import cryptocompare
import datetime
import pandas as pd

In [2]:
test = cryptocompare.get_historical_price_hour('BTC', 'EUR', limit=24)
test

[{'time': 1589731200,
  'close': 8956.77,
  'high': 9054.55,
  'low': 8920.21,
  'open': 9039.98,
  'volumefrom': 1041.29,
  'volumeto': 9344946.7},
 {'time': 1589734800,
  'close': 8985.48,
  'high': 8991.39,
  'low': 8946.92,
  'open': 8956.77,
  'volumefrom': 492.05,
  'volumeto': 4415592.49},
 {'time': 1589738400,
  'close': 8977.37,
  'high': 8985.48,
  'low': 8932.38,
  'open': 8985.48,
  'volumefrom': 417,
  'volumeto': 3739471.46},
 {'time': 1589742000,
  'close': 9005.58,
  'high': 9016.56,
  'low': 8963.01,
  'open': 8977.37,
  'volumefrom': 604.91,
  'volumeto': 5439470.45},
 {'time': 1589745600,
  'close': 8989.99,
  'high': 9007.52,
  'low': 8972.67,
  'open': 9005.58,
  'volumefrom': 496.56,
  'volumeto': 4463601.26},
 {'time': 1589749200,
  'close': 9003.24,
  'high': 9023.38,
  'low': 8983.23,
  'open': 8989.99,
  'volumefrom': 512.52,
  'volumeto': 4615017.45},
 {'time': 1589752800,
  'close': 8935.69,
  'high': 9004.76,
  'low': 8867.84,
  'open': 9003.24,
  'volumefrom': 877.18,
  'volumeto': 7829211.15},
 {'time': 1589756400,
  'close': 8932.05,
  'high': 8976.15,
  'low': 8916.62,
  'open': 8935.69,
  'volumefrom': 256.9,
  'volumeto': 2298992.1},
 {'time': 1589760000,
  'close': 9018.31,
  'high': 9024.14,
  'low': 8931.45,
  'open': 8932.05,
  'volumefrom': 262.43,
  'volumeto': 2361598.62},
 {'time': 1589763600,
  'close': 9112.99,
  'high': 9148.75,
  'low': 9011.33,
  'open': 9018.31,
  'volumefrom': 1461.78,
  'volumeto': 13324888.45},
 {'time': 1589767200,
  'close': 9079.8,
  'high': 9133.38,
  'low': 9054.9,
  'open': 9112.99,
  'volumefrom': 343.55,
  'volumeto': 3126722.41},
 {'time': 1589770800,
  'close': 9075.53,
  'high': 9096.63,
  'low': 9042.05,
  'open': 9079.8,
  'volumefrom': 211.5,
  'volumeto': 1919677.61},
 {'time': 1589774400,
  'close': 9091.77,
  'high': 9118.53,
  'low': 9055.96,
  'open': 9075.53,
  'volumefrom': 235.58,
  'volumeto': 2142999.21},
 {'time': 1589778000,
  'close': 9085.55,
  'high': 9116.54,
  'low': 9075.47,
  'open': 9091.77,
  'volumefrom': 375.64,
  'volumeto': 3417895.91},
 {'time': 1589781600,
  'close': 9020.34,
  'high': 9103.83,
  'low': 8987.03,
  'open': 9085.55,
  'volumefrom': 892.1,
  'volumeto': 8058977.34},
 {'time': 1589785200,
  'close': 9027.96,
  'high': 9048.38,
  'low': 8996.6,
  'open': 9020.34,
  'volumefrom': 451.05,
  'volumeto': 4070831.08},
 {'time': 1589788800,
  'close': 8871.35,
  'high': 9043.5,
  'low': 8787.98,
  'open': 9027.96,
  'volumefrom': 1698.12,
  'volumeto': 15124798.95},
 {'time': 1589792400,
  'close': 8864.25,
  'high': 8913.38,
  'low': 8834.27,
  'open': 8871.35,
  'volumefrom': 1277.02,
  'volumeto': 11336213.88},
 {'time': 1589796000,
  'close': 8912.69,
  'high': 8938.33,
  'low': 8854.38,
  'open': 8864.25,
  'volumefrom': 1038.36,
  'volumeto': 9265522.06},
 {'time': 1589799600,
  'close': 8909.36,
  'high': 8965.38,
  'low': 8909.36,
  'open': 8912.69,
  'volumefrom': 668.08,
  'volumeto': 5971111.3},
 {'time': 1589803200,
  'close': 8927.73,
  'high': 8932.23,
  'low': 8838.66,
  'open': 8909.36,
  'volumefrom': 907.97,
  'volumeto': 8068088.03},
 {'time': 1589806800,
  'close': 8903.63,
  'high': 8938.94,
  'low': 8879.49,
  'open': 8927.73,
  'volumefrom': 534.94,
  'volumeto': 4769105.1},
 {'time': 1589810400,
  'close': 8948.55,
  'high': 8973.47,
  'low': 8886.87,
  'open': 8903.63,
  'volumefrom': 799.13,
  'volumeto': 7148345.32},
 {'time': 1589814000,
  'close': 8872.86,
  'high': 8954.63,
  'low': 8864.47,
  'open': 8948.55,
  'volumefrom': 700.53,
  'volumeto': 6239784.05},
 {'time': 1589817600,
  'close': 8833.94,
  'high': 8906.91,
  'low': 8831.05,
  'open': 8872.86,
  'volumefrom': 378.92,
  'volumeto': 3359181.97}]

In [3]:
test1 = pd.DataFrame(test)
test1

          time    close     high      low     open  volumefrom     volumeto
0   1589731200  8956.77  9054.55  8920.21  9039.98     1041.29   9344946.70
1   1589734800  8985.48  8991.39  8946.92  8956.77      492.05   4415592.49
2   1589738400  8977.37  8985.48  8932.38  8985.48      417.00   3739471.46
3   1589742000  9005.58  9016.56  8963.01  8977.37      604.91   5439470.45
4   1589745600  8989.99  9007.52  8972.67  9005.58      496.56   4463601.26
5   1589749200  9003.24  9023.38  8983.23  8989.99      512.52   4615017.45
6   1589752800  8935.69  9004.76  8867.84  9003.24      877.18   7829211.15
7   1589756400  8932.05  8976.15  8916.62  8935.69      256.90   2298992.10
8   1589760000  9018.31  9024.14  8931.45  8932.05      262.43   2361598.62
9   1589763600  9112.99  9148.75  9011.33  9018.31     1461.78  13324888.45
10  1589767200  9079.80  9133.38  9054.90  9112.99      343.55   3126722.41
11  1589770800  9075.53  9096.63  9042.05  9079.80      211.50   1919677.61
12  1589774400  9091.77  9118.53  9055.96  9075.53      235.58   2142999.21
13  1589778000  9085.55  9116.54  9075.47  9091.77      375.64   3417895.91
14  1589781600  9020.34  9103.83  8987.03  9085.55      892.10   8058977.34
15  1589785200  9027.96  9048.38  8996.60  9020.34      451.05   4070831.08
16  1589788800  8871.35  9043.50  8787.98  9027.96     1698.12  15124798.95
17  1589792400  8864.25  8913.38  8834.27  8871.35     1277.02  11336213.88
18  1589796000  8912.69  8938.33  8854.38  8864.25     1038.36   9265522.06
19  1589799600  8909.36  8965.38  8909.36  8912.69      668.08   5971111.30
20  1589803200  8927.73  8932.23  8838.66  8909.36      907.97   8068088.03
21  1589806800  8903.63  8938.94  8879.49  8927.73      534.94   4769105.10
22  1589810400  8948.55  8973.47  8886.87  8903.63      799.13   7148345.32
23  1589814000  8872.86  8954.63  8864.47  8948.55      700.53   6239784.05
24  1589817600  8833.94  8906.91  8831.05  8872.86      378.92   3359181.97

In [4]:
test1["time"] = pd.to_datetime(test1["time"], unit = "s")

In [5]:
test1

,time,close,high,low,open,volumefrom,volumeto
0,2020-05-17 16:00:00,8956.77,9054.55,8920.21,9039.98,1041.29,9344946.70
1,2020-05-17 17:00:00,8985.48,8991.39,8946.92,8956.77,492.05,4415592.49
2,2020-05-17 18:00:00,8977.37,8985.48,8932.38,8985.48,417.00,3739471.46
3,2020-05-17 19:00:00,9005.58,9016.56,8963.01,8977.37,604.91,5439470.45
4,2020-05-17 20:00:00,8989.99,9007.52,8972.67,9005.58,496.56,4463601.26
5,2020-05-17 21:00:00,9003.24,9023.38,8983.23,8989.99,512.52,4615017.45
6,2020-05-17 22:00:00,8935.69,9004.76,8867.84,9003.24,877.18,7829211.15
7,2020-05-17 23:00:00,8932.05,8976.15,8916.62,8935.69,256.90,2298992.10
8,2020-05-18 00:00:00,9018.31,9024.14,8931.45,8932.05,262.43,2361598.62
9,2020-05-18 01:00:00,9112.99,9148.75,9011.33,9018.31,1461.78,13324888.45
10,2020-05-18 02:00:00,9079.80,9133.38,9054.90,9112.99,343.55,3126722.41
11,2020-05-18 03:00:00,9075.53,9096.63,9042.05,9079.80,211.50,1919677.61
12,2020-05-18 04:00:00,9091.77,9118.53,9055.96,9075.53,235.58,2142999.21
13,2020-05-18 05:00:00,9085.55,9116.54,9075.47,9091.77,375.64,3417895.91
14,2020-05-18 06:00:00,9020.34,9103.83,8987.03,9085.55,892.10,8058977.34
15,2020-05-18 07:00:00,9027.96,9048.38,8996.60,9020.34,451.05,4070831.08
16,2020-05-18 08:00:00,8871.35,9043.50,8787.98,9027.96,1698.12,15124798.95
17,2020-05-18 09:00:00,8864.25,8913.38,8834.27,8871.35,1277.02,11336213.88
18,2020-05-18 10:00:00,8912.69,8938.33,8854.38,8864.25,1038.36,9265522.06
19,2020-05-18 11:00:00,8909.36,8965.38,8909.36,8912.69,668.08,5971111.30
20,2020-05-18 12:00:00,8927.73,8932.23,8838.66,8909.36,907.97,8068088.03
21,2020-05-18 13:00:00,8903.63,8938.94,8879.49,8927.73,534.94,4769105.10
22,2020-05-18 14:00:00,8948.55,8973.47,8886.87,8903.63,799.13,7148345.32
23,2020-05-18 15:00:00,8872.86,8954.63,8864.47,8948.55,700.53,6239784.05
24,2020-05-18 16:00:00,8833.94,8906.91,8831.05,8872.86,378.92,3359181.97